name: Auto Release

on:
  schedule:
    - cron: "0 6 1 * *" # 1st of month, 06:00 UTC
  workflow_dispatch:

jobs:
  release:
    uses: alexander-zimmermann/lares/.github/workflows/sidecar-python-auto-release.yaml@73c26719e34f618c045a88dcc3626c5c5733ae77 # main
    secrets: inherit
