name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: alexander-zimmermann/lares/.github/workflows/sidecar-python-ci.yaml@1fde31ac34875a6947163e6c40120adddb2e70d8 # main
