name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: alexander-zimmermann/lares/.github/workflows/sidecar-python-ci.yaml@871e66b962bc75ba789935a32dcd58f2fb2cceb9 # main
