name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to build (e.g. v0.1.0)"
        required: true

jobs:
  image:
    permissions:
      contents: read
      packages: write
    uses: alexander-zimmermann/lares/.github/workflows/sidecar-python-release.yaml@3026f13fed2f3e9cc6bdb87b30d458f8751de31a # main
    with:
      tag: ${{ github.event.inputs.tag || '' }}
