name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to build (e.g. v0.1.0)"
        required: true

jobs:
  image:
    permissions:
      contents: read
      packages: write
    uses: alexander-zimmermann/lares/.github/workflows/sidecar-python-release.yaml@7242155b246a20775b04ffb7b7bd89593f0d9c8f # main
    with:
      tag: ${{ github.event.inputs.tag || '' }}
